WDL-OL/IPlug: IPlugUtilities.h File Reference
IPlugUtilities.h File Reference
Utility functions and macros.
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cctype>
#include "wdlstring.h"
#include "IPlugConstants.h"
#include "IPlugPlatform.h"
Macros
#define FREE_NULL(p) {free(p);p=nullptr;}
#define DELETE_NULL(p) {delete(p); p=nullptr;}
#define DELETE_ARRAY(p) {delete[](p); (p)=nullptr;}
#define MAKE_QUOTE(str) #str
#define MAKE_STR(str) MAKE_QUOTE(str)
#define GET_PARAM_FROM_VARARG(paramType, vp, v)
Functions
template<typename T >
T Clip (T x, T lo, T hi)
Clips the value x between lo and hi.
static bool CStringHasContents (const char *str)
static double DBToAmp (double dB)
Calculates gain from a given dB value.
static double AmpToDB (double amp)
static void GetVersionParts (int version, int &ver, int &maj, int &min)
static int GetDecimalVersion (int version)
static void GetVersionStr (int version, WDL_String &str)
template<class SRC , class DEST >
void CastCopy (DEST *pDest, SRC *pSrc, int n)
static void ToLower (char *cDest, const char *cSrc)
void BasicTextMeasure (const char *txt, float &numLines, float &maxLineWidth)
static EHost LookUpHost (const char *inHost)
Gets the host ID from a human-readable name.
static void GetHostNameStr (EHost host, char *pHostName)
Gets a human-readable name from host identifier.
static void MidiNoteName (double midiPitch, WDL_String &noteName, bool cents=false)
Detailed Description
Utility functions and macros.
Definition in file IPlugUtilities.h.
Function Documentation
static double AmpToDB (double amp) inline static
Returns
dB calculated as an approximation of \(20*log_{10}(x) \)
See Also
AMP_DB
Definition at line 91 of file IPlugUtilities.h.
References AMP_DB.
template<typename T > T Clip (T x, T lo, T hi)
Clips the value x between lo and hi.
Parameters
x Input value
lo Minimum value to be allowed
hi Maximum value to be allowed If x is outside given range, it will be set to one of the boundaries
Definition at line 40 of file IPlugUtilities.h.
Referenced by IGraphics::DrawBitmap(), IGraphics::DrawHorizontalLine(), and IGraphics::DrawVerticalLine().
static double DBToAmp (double dB) inline static
Calculates gain from a given dB value.
Parameters
dB Value in dB
Returns
Gain calculated as an approximation of \(10^{\frac{x}{20}} \)
See Also
IAMP_DB
Definition at line 81 of file IPlugUtilities.h.
References IAMP_DB.
static void GetHostNameStr (EHost host, char * pHostName) static
Gets a human-readable name from host identifier.
Parameters
host Host identifier (see EHost)
pHostName Pointer to a string to write to
int hostID = EHost::kHostAbletonLive;
char buffer[20];
GetHostNameStr(hostID, buffer);
The longest string returned by GetHostNameStr is 18 characters long (+1 for the null terminator). Make sure your buffer can handle the size!
Definition at line 212 of file IPlugUtilities.h.
static EHost LookUpHost (const char * inHost) static
Gets the host ID from a human-readable name.
Parameters
inHost Host name to search for
Returns
Identifier of the host (see EHost)
Definition at line 159 of file IPlugUtilities.h.
Referenced by IPlugBase::SetHost().