WDL-OL/IPlug: IPlugProcessor< T > Class Template Reference
IPlugProcessor< T > Class Template Reference abstract
The base class for IPlug Audio Processing.
#include <IPlugProcessor.h>
Public Member Functions
IPlugProcessor (IPlugConfig config, EAPI plugAPI)
virtual void ProcessBlock (T **inputs, T **outputs, int nFrames)
Override in your plug-in class to process audio In ProcessBlock you are always guaranteed to get valid pointers to all the channels the plugin requested (the maximum possible input channel count and the maximum possible output channel count including multiple buses).
virtual void ProcessMidiMsg (const IMidiMsg &msg)
Override this method to handle incoming MIDI messages.
virtual void ProcessSysEx (ISysEx &msg)
Override this method to handle incoming MIDI System Exclusive (SysEx) messages.
virtual void OnReset ()
Override this method in your plug-in class to do something prior to playback etc.
virtual void OnActivate (bool active)
Override OnActivate() which should be called by the API class when a plug-in is "switched on" by the host on a track when the channel count is known.
virtual bool SendMidiMsg (const IMidiMsg &msg)=0
Send a single MIDI message.
bool SendMidiMsgs (WDL_TypedBuf< IMidiMsg > &msgs)
Send a collection of MIDI messages.
virtual bool SendSysEx (ISysEx &msg)
Send a single MIDI System Exclusive (SysEx) message.
double GetSampleRate () const
int GetBlockSize () const
int GetLatency () const
int GetTailSize ()
bool GetBypassed () const
bool GetRenderingOffline () const
int GetSamplePos () const
double GetTempo () const
double GetSamplesPerBeat () const
void GetTimeSig (int &numerator, int &denominator)
int NIOConfigs () const
IOConfig * GetIOConfig (int idx)
int MaxNBuses (ERoute direction) const
Used to determine the maximum number of input or output buses based on what was specified in the channel I/O config string.
int MaxNChannelsForBus (ERoute direction, int busIdx) const
For a given input or output bus what is the maximum possible number of channels.
bool HasWildcardBus (ERoute direction) const
Check if we have any wildcard characters in the channel I/O configs.
int MaxNChannels (ERoute direction) const
bool IsChannelConnected (ERoute direction, int chIdx) const
int NChannelsConnected (ERoute direction) const
int NInChansConnected ()
Convenience method to find out how many input channels are connected.
int NOutChansConnected ()
Convenience method to find out how many output channels are connected.
bool LegalIO (int NInputChans, int NOutputChans) const
Check if a certain configuration of input channels and output channels is allowed based on the channel I/O configs.
bool HasSidechainInput () const
int NSidechainChannels () const
void LimitToStereoIO ()
This is called by IPlugVST in order to limit a plug-in to stereo I/O for certain picky hosts.
bool IsInstrument () const
bool DoesMIDI () const
void SetChannelLabel (ERoute direction, int idx, const char *formatStr, bool zeroBased=false)
This allows you to label input/output channels in supporting VST2 hosts.
virtual void SetLatency (int latency)
Call this if the latency of your plug-in changes after initialization (perhaps from OnReset()) This may not be supported by the host.
void SetTailSize (int tailSize)
Call this method if you need to update the tail size at runtime, for example if the decay time of your reverb effect changes Some apis have special interpretations of certain numbers.
void _SetSampleRate (double sampleRate)
void _SetBlockSize (int blockSize)
void _SetBypassed (bool bypassed)
void _SetTimeInfo (const ITimeInfo &timeInfo)
void _SetRenderingOffline (bool renderingOffline)
const WDL_String & _GetChannelLabel (ERoute direction, int idx)
Static Public Member Functions
static int ParseChannelIOStr (const char *IOStr, WDL_PtrList< IOConfig > &channelIOList, int &totalNInChans, int &totalNOutChans, int &totalNInBuses, int &totalNOutBuses)
A static method to parse the config.h channel I/O string.
Protected Member Functions
void _SetChannelConnections (ERoute direction, int idx, int n, bool connected)
void _AttachBuffers (ERoute direction, int idx, int n, PLUG_SAMPLE_DST **ppData, int nFrames)
void _AttachBuffers (ERoute direction, int idx, int n, PLUG_SAMPLE_SRC **ppData, int nFrames)
void _PassThroughBuffers (PLUG_SAMPLE_SRC type, int nFrames)
void _PassThroughBuffers (PLUG_SAMPLE_DST type, int nFrames)
void _ProcessBuffers (PLUG_SAMPLE_SRC type, int nFrames)
void _ProcessBuffers (PLUG_SAMPLE_DST type, int nFrames)
void _ProcessBuffersAccumulating (int nFrames)
void _ZeroScratchBuffers ()
Protected Attributes
NChanDelayLine< T > * mLatencyDelay = nullptr
Pointer to a multichannel delay line used to delay the bypassed signal when a plug-in with latency is bypassed.
Detailed Description
template<typename T>
class IPlugProcessor< T >
The base class for IPlug Audio Processing.
It knows nothing about presets or parameters or user interface.
Definition at line 23 of file IPlugProcessor.h.
Member Function Documentation
template<typename T> bool IPlugProcessor< T >::DoesMIDI () const inline
Returns
true if the plug-in was configured to receive midi at compile time
Definition at line 172 of file IPlugProcessor.h.
template<typename T> int IPlugProcessor< T >::GetBlockSize () const inline
Returns
Current block size in samples
Definition at line 81 of file IPlugProcessor.h.
template<typename T> bool IPlugProcessor< T >::GetBypassed () const inline
Returns
true if the plugin is currently bypassed
Definition at line 90 of file IPlugProcessor.h.
template<typename T> IOConfig* IPlugProcessor< T >::GetIOConfig (int idx) inline
Returns
Pointer to an IOConfig at idx. Can return nullptr if idx is invalid
Definition at line 114 of file IPlugProcessor.h.
template<typename T> int IPlugProcessor< T >::GetLatency () const inline
Returns
Plugin latency (in samples)
Definition at line 84 of file IPlugProcessor.h.
template<typename T> bool IPlugProcessor< T >::GetRenderingOffline () const inline
Returns
true if the plugin is currently rendering off-line
Definition at line 93 of file IPlugProcessor.h.
template<typename T> int IPlugProcessor< T >::GetSamplePos () const inline
Returns
The number of samples elapsed since start of project timeline.
Definition at line 97 of file IPlugProcessor.h.
template<typename T> double IPlugProcessor< T >::GetSampleRate () const inline
Returns
Sample rate (in Hz)
Definition at line 78 of file IPlugProcessor.h.
template<typename T > double IPlugProcessor< T >::GetSamplesPerBeat () const
Returns
The number of samples in a beat
Definition at line 103 of file IPlugProcessor.cpp.
template<typename T> int IPlugProcessor< T >::GetTailSize () inline
Returns
The tail size in samples (useful for reverberation plug-ins, that may need to decay after the transport stops or an audio item ends)
Definition at line 87 of file IPlugProcessor.h.
template<typename T> double IPlugProcessor< T >::GetTempo () const inline
Returns
The Tempo in beats per minute
Definition at line 100 of file IPlugProcessor.h.
template<typename T> void IPlugProcessor< T >::GetTimeSig (int & numerator, int & denominator) inline
Parameters
numerator The upper part of the current time signature e.g "6" in the time signature 6/8
denominator The lower part of the current time signature e.g "8" in the time signature 6/8
Definition at line 107 of file IPlugProcessor.h.
template<typename T> bool IPlugProcessor< T >::HasSidechainInput () const inline
Returns
true if this plug-in has a side-chain input, which may not necessarily be active in the current I/O config
Definition at line 160 of file IPlugProcessor.h.
template<typename T> bool IPlugProcessor< T >::HasWildcardBus (ERoute direction) const inline
Check if we have any wildcard characters in the channel I/O configs.
Parameters
direction Return input or output bus count
Returns
true if the bus has a wildcard, meaning it should work on any number of channels
Definition at line 130 of file IPlugProcessor.h.
template<typename T> bool IPlugProcessor< T >::IsChannelConnected (ERoute direction, int chIdx) const inline
Parameters
direction Whether you want to test inputs or outputs
chIdx channel index
Returns
true if the host has connected this channel
Definition at line 139 of file IPlugProcessor.h.
template<typename T> bool IPlugProcessor< T >::IsInstrument () const inline
Returns
true if the plug-in was configured as an instrument at compile time
Definition at line 169 of file IPlugProcessor.h.
template<typename T > bool IPlugProcessor< T >::LegalIO (int NInputChans, int NOutputChans) const
Check if a certain configuration of input channels and output channels is allowed based on the channel I/O configs.
Parameters
NInputChans Number of inputs to test, if set to -1 = check NOutputChans only
NOutputChans Number of outputs to test, if set to -1 = check NInputChans only
Returns
true if the configurations is valid
Definition at line 165 of file IPlugProcessor.cpp.
References IOConfig::GetTotalNChannels().
template<typename T > void IPlugProcessor< T >::LimitToStereoIO ()
This is called by IPlugVST in order to limit a plug-in to stereo I/O for certain picky hosts.
Todo:
may no longer be relevant
Definition at line 180 of file IPlugProcessor.cpp.
template<typename T > int IPlugProcessor< T >::MaxNBuses (ERoute direction) const
Used to determine the maximum number of input or output buses based on what was specified in the channel I/O config string.
Parameters
direction Return input or output bus count
Returns
The maximum bus count across all channel I/O configs
Definition at line 116 of file IPlugProcessor.cpp.
Referenced by IPlugProcessor< float >::HasSidechainInput().
template<typename T> int IPlugProcessor< T >::MaxNChannels (ERoute direction) const inline
Parameters
direction Whether you want to test inputs or outputs
Returns
Total number of input or output channel buffers (not necessarily connected)
Definition at line 134 of file IPlugProcessor.h.
template<typename T > int IPlugProcessor< T >::MaxNChannelsForBus (ERoute direction, int busIdx) const
For a given input or output bus what is the maximum possible number of channels.
Parameters
direction Return input or output bus count
busIdx The index of the bus to look up
Returns
return The maximum number of channels on that bus
Definition at line 129 of file IPlugProcessor.cpp.
template<typename T > int IPlugProcessor< T >::NChannelsConnected (ERoute direction) const
Parameters
direction Whether you want to test inputs or outputs
Returns
The number of channels connected for input/output. WARNING: this assumes consecutive channel connections
Definition at line 151 of file IPlugProcessor.cpp.
Referenced by IPlugProcessor< float >::NInChansConnected(), and IPlugProcessor< float >::NOutChansConnected().
template<typename T> int IPlugProcessor< T >::NInChansConnected () inline
Convenience method to find out how many input channels are connected.
Returns
The number of channels connected for input. WARNING: this assumes consecutive channel connections
Definition at line 147 of file IPlugProcessor.h.
template<typename T> int IPlugProcessor< T >::NIOConfigs () const inline
Returns
The number of channel I/O configs derived from the channel io string
Definition at line 111 of file IPlugProcessor.h.
template<typename T> int IPlugProcessor< T >::NOutChansConnected () inline
Convenience method to find out how many output channels are connected.
Returns
The number of channels connected for output. WARNING: this assumes consecutive channel connections
Definition at line 151 of file IPlugProcessor.h.
template<typename T> int IPlugProcessor< T >::NSidechainChannels () const inline
Returns
The number of channels and the side-chain input
Todo:
this will change
Definition at line 163 of file IPlugProcessor.h.
template<typename T> virtual void IPlugProcessor< T >::OnActivate (bool active) inline virtual
Override OnActivate() which should be called by the API class when a plug-in is "switched on" by the host on a track when the channel count is known.
This may not work reliably because different hosts have different interpretations of "activate". Unlike OnReset() which called when the transport is reset or the sample rate changes OnActivate() is a good place to handle change of I/O connections.
Parameters
active true if the host has activated the plug-in
Definition at line 58 of file IPlugProcessor.h.
template<typename T> virtual void IPlugProcessor< T >::OnReset () inline virtual
Override this method in your plug-in class to do something prior to playback etc.
(e.g.clear buffers, update internal DSP with the latest sample rate)
Definition at line 52 of file IPlugProcessor.h.
template<typename T > int IPlugProcessor< T >::ParseChannelIOStr (const char * IOStr, WDL_PtrList< IOConfig > & channelIOList, int & totalNInChans, int & totalNOutChans, int & totalNInBuses, int & totalNOutBuses) static
A static method to parse the config.h channel I/O string.
Parameters
IOStr Space separated cstring list of I/O configurations for this plug-in in the format ninchans-noutchans. A hypen character (-) deliminates input-output. Supports multiple buses, which are indicated using a period (.) character. For instance plug-in that supports mono input and mono output with a mono side-chain input could have a channel io string of "1.1-1". A drum synthesiser with four stereo output busses could be configured with a io string of "0-2.2.2.2";
channelIOList A list of pointers to ChannelIO structs, where we will store here
totalNInChans The total number of input channels across all buses will be stored here
totalNOutChans The total number of output channels across all buses will be stored here
totalNInBuses The total number of input buses across all channel I/O configs will be stored here
totalNOutBuses The total number of output buses across all channel I/O configs will be stored here
Returns
The number of space separated channel I/O configs that have been detected in IOStr
Definition at line 207 of file IPlugProcessor.cpp.
template<typename T> void IPlugProcessor< T >::ProcessBlock (T ** inputs, T ** outputs, int nFrames) virtual
Override in your plug-in class to process audio In ProcessBlock you are always guaranteed to get valid pointers to all the channels the plugin requested (the maximum possible input channel count and the maximum possible output channel count including multiple buses).
If the host hasn't connected all the pins, the unconnected channels will be full of zeros. THIS METHOD IS CALLED BY THE HIGH PRIORITY AUDIO THREAD - You should be careful not to do any unbounded, blocking operations such as file I/O which could cause audio dropouts
Parameters
inputs Two-dimensional array containing the non-interleaved input buffers of audio samples for all channels
outputs Two-dimensional array for audio output (non-interleaved).
nFrames The block size for this block: number of samples per channel.
Definition at line 65 of file IPlugProcessor.cpp.
template<typename T > void IPlugProcessor< T >::ProcessMidiMsg (const IMidiMsg & msg) virtual
Override this method to handle incoming MIDI messages.
The method is called prior to ProcessBlock(). You can use IMidiQueue in combination with this method in order to queue the message and process at the appropriate time in ProcessBlock() THIS METHOD IS CALLED BY THE HIGH PRIORITY AUDIO THREAD - You should be careful not to do any unbounded, blocking operations such as file I/O which could cause audio dropouts
Parameters
msg The incoming midi message (includes a timestamp to indicate the offset in the forthcoming block of audio to be processed in ProcessBlock())
Definition at line 85 of file IPlugProcessor.cpp.
template<typename T> virtual void IPlugProcessor< T >::ProcessSysEx (ISysEx & msg) inline virtual
Override this method to handle incoming MIDI System Exclusive (SysEx) messages.
The method is called prior to ProcessBlock(). THIS METHOD IS CALLED BY THE HIGH PRIORITY AUDIO THREAD - You should be careful not to do any unbounded, blocking operations such as file I/O which could cause audio dropouts
Definition at line 49 of file IPlugProcessor.h.
template<typename T> virtual bool IPlugProcessor< T >::SendMidiMsg (const IMidiMsg & msg) pure virtual
Send a single MIDI message.
Parameters
msg The IMidiMsg to send
Returns
true if successful
Implemented in IPlugAAX, IPlugAU, IPlugVST3, IPlugAPP, IPlugVST3Processor, IPlugWAM, and IPlugVST2.
template<typename T > bool IPlugProcessor< T >::SendMidiMsgs (WDL_TypedBuf< IMidiMsg > & msgs)
Send a collection of MIDI messages.
Parameters
msg The IMidiMsg to send
Returns
true if successful
Definition at line 91 of file IPlugProcessor.cpp.
template<typename T> virtual bool IPlugProcessor< T >::SendSysEx (ISysEx & msg) inline virtual
Send a single MIDI System Exclusive (SysEx) message.
Parameters
msg The ISysEx to send
Returns
true if successful
Reimplemented in IPlugAPP, IPlugWAM, and IPlugVST2.
Definition at line 75 of file IPlugProcessor.h.
template<typename T > void IPlugProcessor< T >::SetChannelLabel (ERoute direction, int idx, const char * formatStr, bool zeroBased = false)
This allows you to label input/output channels in supporting VST2 hosts.
For example a 4 channel plug-in that deals with FuMa BFormat first order ambisonic material, might label these channels "W", "X", "Y", "Z", rather than the default "input 1", "input 2", "input 3", "input 4"
Parameters
idx The index of the channel that you wish to label
limited printf style format string to compose label for the channel - where i will be the channel index
zeroBased If true the index in the format string will be zero based
Definition at line 190 of file IPlugProcessor.cpp.
template<typename T > void IPlugProcessor< T >::SetLatency (int latency) virtual
Call this if the latency of your plug-in changes after initialization (perhaps from OnReset()) This may not be supported by the host.
The method is virtual because it's overridden in API classes.
Parameters
samples Latency in samples
Reimplemented in IPlugAAX, IPlugAU, IPlugVST3, IPlugWAM, and IPlugVST2.
Definition at line 197 of file IPlugProcessor.cpp.
Referenced by IPlugVST2::SetLatency(), IPlugVST3::SetLatency(), IPlugAU::SetLatency(), and IPlugAAX::SetLatency().
template<typename T> void IPlugProcessor< T >::SetTailSize (int tailSize) inline
Call this method if you need to update the tail size at runtime, for example if the decay time of your reverb effect changes Some apis have special interpretations of certain numbers.
For VST3 set to 0xffffffff for infinite tail, or 0 for none (default) For VST2 setting to 1 means no tail
Parameters
tailSizeSamples the new tailsize in samples
Definition at line 191 of file IPlugProcessor.h.
Member Data Documentation
template<typename T> NChanDelayLine<T>* IPlugProcessor< T >::mLatencyDelay = nullptr protected
Pointer to a multichannel delay line used to delay the bypassed signal when a plug-in with latency is bypassed.
Definition at line 256 of file IPlugProcessor.h.
The documentation for this class was generated from the following files:
IPlugProcessor.h
IPlugProcessor.cpp