WDL-OL/IPlug: IGraphicsDelegate Class Reference
IGraphicsDelegate Class Reference
An IDelgate base class for a SOMETHING that uses IGraphics for it's UI.
#include <IPlugGraphicsDelegate.h>
Public Member Functions
IGraphicsDelegate (int nParams)
void * OpenWindow (void *pHandle) override
Override this method when not using IGraphics in order to return a platform view handle e.g.
void CloseWindow () override
Override this method when not using IGraphics if you need to free resources etc when the window closes.
virtual void SetControlValueFromDelegate (int controlTag, double normalizedValue) override
In IGraphics plug-ins, this method is used to update IControls in the user interface from the plug-in class, when the control is not linked to a parameter, for example a typical use case would be a meter control.
virtual void SendControlMsgFromDelegate (int controlTag, int messageTag, int dataSize, const void *pData) override
virtual void OnMidiMsgUI (const IMidiMsg &msg) override
void SendParameterValueToUIFromDelegate (int paramIdx, double value, bool normalized) override
This method is called by the class implementing DELEGATE, NOT THE PLUGIN API class in order to update the user interface with the new parameter values, typically after automation.
void ResizeGraphicsFromUI () override
Sometimes when a plug-in wants to change its UI dimensions we need to call into the plug-in api class first when we click a button in our UI This method is implemented in various classes that inherit this interface to implement that behaviour.
virtual void OnRestoreState () override
If you override this method you should call this parent, or implement the same functionality in order to get controls to update, when state is restored.
virtual void AttachGraphics (IGraphics *pGraphics)
virtual IGraphics * GetUI ()
Public Member Functions inherited from IDelegate
IDelegate (int nParams)
IParam * GetParam (int paramIdx)
Get a pointer to one of the delegate's IParam objects.
int NParams () const
virtual void OnParamChangeUI (int paramIdx)
This is an OnParamChange that will only trigger on the UI thread at low priority, and therefore is appropriate for hiding or showing elements of the UI.
virtual void OnSysexMsgUI (int size, const void *pData)
virtual bool OnMessage (const char *msgID, int dataSize, const void *pData)
This could be implemented in either DSP or EDITOR to receive a message from the other one.
virtual void SendMsgFromDelegate (const char *msg, int dataSize, const void *pData)
virtual void BeginInformHostOfParamChangeFromUI (int paramIdx)=0
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
virtual void SetParameterValueFromUI (int paramIdx, double normalizedValue)
Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
virtual void EndInformHostOfParamChangeFromUI (int paramIdx)=0
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
virtual void SendMidiMsgFromUI (const IMidiMsg &msg)
When we want to send a MIDI message from the UI for example clicking on a key in a virtual keyboard, this method should be used.
virtual void SendSysexMsgFromUI (int size, const uint8_t *pData)
virtual void SendMsgFromUI (const char *msgID, int dataSize=0, const void *pData=nullptr)
Additional Inherited Members
Protected Attributes inherited from IDelegate
WDL_PtrList< IParam > mParams
A list of IParam objects.
Detailed Description
An IDelgate base class for a SOMETHING that uses IGraphics for it's UI.
Definition at line 13 of file IPlugGraphicsDelegate.h.
Member Function Documentation
void IGraphicsDelegate::OnRestoreState () override virtual
If you override this method you should call this parent, or implement the same functionality in order to get controls to update, when state is restored.
Reimplemented from IDelegate.
Definition at line 31 of file IPlugGraphicsDelegate.cpp.
References IDelegate::mParams, and SendParameterValueToUIFromDelegate().
void * IGraphicsDelegate::OpenWindow (void * pHandle) override virtual
Override this method when not using IGraphics in order to return a platform view handle e.g.
NSView, UIView, HWND
Reimplemented from IDelegate.
Definition at line 44 of file IPlugGraphicsDelegate.cpp.
References IGraphics::OpenWindow().
void IGraphicsDelegate::SendParameterValueToUIFromDelegate (int paramIdx, double value, bool normalized) override virtual
This method is called by the class implementing DELEGATE, NOT THE PLUGIN API class in order to update the user interface with the new parameter values, typically after automation.
This method should only be called from the main thread. The similarly named IPlugBase::_SendParameterValueToUIFromAPI() should take care of queueing and deferring, if there is no main thread notification from the API If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered In IGraphics plug-ins, this will update any IControls that have their mParamIdx set > -1
Parameters
paramIdx The index of the parameter to be updated
value The new value of the parameter
normalized true if value is normalised
Reimplemented from IDelegate.
Definition at line 112 of file IPlugGraphicsDelegate.cpp.
References IGraphics::GetControl(), IDelegate::GetParam(), IGraphics::NControls(), IControl::ParamIdx(), IDelegate::SendParameterValueToUIFromDelegate(), and IControl::SetValueFromDelegate().
Referenced by OnRestoreState().
void IGraphicsDelegate::SetControlValueFromDelegate (int controlTag, double normalizedValue) override virtual
In IGraphics plug-ins, this method is used to update IControls in the user interface from the plug-in class, when the control is not linked to a parameter, for example a typical use case would be a meter control.
It is called by the IPlug "user" a.k.a you - not by an API class. In OnIdle() your plug-in would call this method to update the IControl's value. YOU SHOULD NOT CALL THIS ON THE AUDIO THREAD! If you are not using IGraphics, you could use it in a similar way, as long as your control/meter has a unique tag
Parameters
controlTag A tag for the control
normalizedValue The normalised value to set the control to. This will modify IControl::mValue;
Reimplemented from IDelegate.
Definition at line 76 of file IPlugGraphicsDelegate.cpp.
References IGraphics::GetControl(), IGraphics::NControls(), and IControl::SetValueFromDelegate().
The documentation for this class was generated from the following files:
IPlugGraphicsDelegate.h
IPlugGraphicsDelegate.cpp