WDL-OL/IPlug: IDelegate Class Reference
IDelegate Class Reference abstract
This pure virtual interface delegates communication in both directions between a UI editor and something else (which is usually a plug-in) It is also the class that owns parameter objects (for historical reasons) - although it's not necessary to allocate them.
#include <IPlugDelegate.h>
Public Member Functions
IDelegate (int nParams)
IParam * GetParam (int paramIdx)
Get a pointer to one of the delegate's IParam objects.
int NParams () const
virtual void * OpenWindow (void *pHandle)
Override this method when not using IGraphics in order to return a platform view handle e.g.
virtual void CloseWindow ()
Override this method when not using IGraphics if you need to free resources etc when the window closes.
virtual void OnParamChangeUI (int paramIdx)
This is an OnParamChange that will only trigger on the UI thread at low priority, and therefore is appropriate for hiding or showing elements of the UI.
virtual void OnMidiMsgUI (const IMidiMsg &msg)
virtual void OnSysexMsgUI (int size, const void *pData)
virtual bool OnMessage (const char *msgID, int dataSize, const void *pData)
This could be implemented in either DSP or EDITOR to receive a message from the other one.
virtual void OnRestoreState ()
This is called by API classes after restoring state and by IPluginDelegate::RestorePreset().
virtual void SetControlValueFromDelegate (int controlTag, double normalizedValue)
In IGraphics plug-ins, this method is used to update IControls in the user interface from the plug-in class, when the control is not linked to a parameter, for example a typical use case would be a meter control.
virtual void SendControlMsgFromDelegate (int controlTag, int messageTag, int dataSize, const void *pData)
virtual void SendMsgFromDelegate (const char *msg, int dataSize, const void *pData)
virtual void SendParameterValueToUIFromDelegate (int paramIdx, double value, bool normalized)
This method is called by the class implementing DELEGATE, NOT THE PLUGIN API class in order to update the user interface with the new parameter values, typically after automation.
virtual void BeginInformHostOfParamChangeFromUI (int paramIdx)=0
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
virtual void SetParameterValueFromUI (int paramIdx, double normalizedValue)
Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
virtual void EndInformHostOfParamChangeFromUI (int paramIdx)=0
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
virtual void ResizeGraphicsFromUI ()
Sometimes when a plug-in wants to change its UI dimensions we need to call into the plug-in api class first when we click a button in our UI This method is implemented in various classes that inherit this interface to implement that behaviour.
virtual void SendMidiMsgFromUI (const IMidiMsg &msg)
When we want to send a MIDI message from the UI for example clicking on a key in a virtual keyboard, this method should be used.
virtual void SendSysexMsgFromUI (int size, const uint8_t *pData)
virtual void SendMsgFromUI (const char *msgID, int dataSize=0, const void *pData=nullptr)
Protected Attributes
WDL_PtrList< IParam > mParams
A list of IParam objects.
Detailed Description
This pure virtual interface delegates communication in both directions between a UI editor and something else (which is usually a plug-in) It is also the class that owns parameter objects (for historical reasons) - although it's not necessary to allocate them.
In distributed plug-in architectures, certain methods are implemented using
It needn't be a "plug-in" that implements this interface, it can also be used for other things An example use case: you would like to pop up a custom preferences window with a few simple checkboxes. You should be able to do that with a new graphics context and something implementing this interface in order to send/receive values to/from your new UI.
Note on method names: "FromUI" in a method name, means that that method is called by the UI class. Likewise "ToUI" means that the method is delivering something wait for it... to the UI. The words "FromDelegate" in a method name mean that method is called from the class that implements the IDelegate interface, which is usually your plug-in base class, but may not be in the case of an isolated editor class, or if you are using IGraphics without IPlug, and your IDelegate is not a plug-in
NOTES: A parameter VALUE is a floating point number linked to an integer parameter index. TODO: Normalised ? A parameter OBJECT (IParam) is an instance of the IParam class as defined in IPlugParameter.h A parameter OBJECT is also referred to as a "param", in method names such as IDelegate::GetParam(int paramIdx) and IControl::GetParam().
Definition at line 31 of file IPlugDelegate.h.
Member Function Documentation
virtual void IDelegate::BeginInformHostOfParamChangeFromUI (int paramIdx) pure virtual
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
Parameters
paramIdx The index of the parameter that is changing value
Implemented in IPlugBase.
Referenced by IGraphics::OnMouseDown().
virtual void IDelegate::EndInformHostOfParamChangeFromUI (int paramIdx) pure virtual
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
Parameters
paramIdx The index of the parameter that is changing value
Implemented in IPlugBase.
Referenced by IGraphics::OnMouseUp().
IParam* IDelegate::GetParam (int paramIdx) inline
Get a pointer to one of the delegate's IParam objects.
Parameters
paramIdx The index of the parameter object to be got
Returns
A pointer to the IParam object at paramIdx or nullptr if paramIdx is invalid
Definition at line 48 of file IPlugDelegate.h.
References mParams.
Referenced by IGraphics::ClampControl(), IPluginDelegate::CloneParamRange(), IPlugBase::CompareState(), IPluginDelegate::CopyParamValues(), IPlugBase::DirtyParameters(), IPluginDelegate::ForParamInGroup(), IPluginDelegate::ForParamInRange(), IPluginDelegate::InitFromDelegate(), IPluginDelegate::InitParamRange(), IGraphicsDelegate::SendParameterValueToUIFromDelegate(), IPlugBase::SetParameterValue(), and SetParameterValueFromUI().
int IDelegate::NParams () const inline
Returns
Returns the number of parameters that belong to the plug-in.
Definition at line 51 of file IPlugDelegate.h.
References mParams.
Referenced by IPlugBase::CompareState(), IPluginDelegate::CopyParamValues(), IPlugBase::DirtyParameters(), IPluginDelegate::ForParamInGroup(), IPluginDelegate::InitFromDelegate(), and SetParameterValueFromUI().
virtual bool IDelegate::OnMessage (const char * msgID, int dataSize, const void * pData) inline virtual
This could be implemented in either DSP or EDITOR to receive a message from the other one.
Parameters
msg <#msg description#>
dataSize <#dataSize description#>
pData <#pData description#>
Returns
<#return value description#>
Definition at line 81 of file IPlugDelegate.h.
virtual void IDelegate::OnParamChangeUI (int paramIdx) inline virtual
This is an OnParamChange that will only trigger on the UI thread at low priority, and therefore is appropriate for hiding or showing elements of the UI.
You should not update parameter objects using this method.
Parameters
paramIdx The index of the parameter that changed
Definition at line 64 of file IPlugDelegate.h.
Referenced by SendParameterValueToUIFromDelegate(), and SetParameterValueFromUI().
virtual void IDelegate::OnRestoreState () inline virtual
This is called by API classes after restoring state and by IPluginDelegate::RestorePreset().
Typically used to update user interface, where multiple parameter values have changed. If you need to do something when state is restored you can override it
Reimplemented in IGraphicsDelegate.
Definition at line 85 of file IPlugDelegate.h.
virtual void* IDelegate::OpenWindow (void * pHandle) inline virtual
Override this method when not using IGraphics in order to return a platform view handle e.g.
NSView, UIView, HWND
Reimplemented in IGraphicsDelegate.
Definition at line 56 of file IPlugDelegate.h.
virtual void IDelegate::SendMidiMsgFromUI (const IMidiMsg & msg) inline virtual
When we want to send a MIDI message from the UI for example clicking on a key in a virtual keyboard, this method should be used.
Parameters
status The status byte of the MIDI message
data1 The first data byte of the MIDI message
data2 The second data byte of the MIDI message
Reimplemented in IPlugBase, and IPlugVST3Controller.
Definition at line 148 of file IPlugDelegate.h.
virtual void IDelegate::SendParameterValueToUIFromDelegate (int paramIdx, double value, bool normalized) inline virtual
This method is called by the class implementing DELEGATE, NOT THE PLUGIN API class in order to update the user interface with the new parameter values, typically after automation.
This method should only be called from the main thread. The similarly named IPlugBase::_SendParameterValueToUIFromAPI() should take care of queueing and deferring, if there is no main thread notification from the API If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered In IGraphics plug-ins, this will update any IControls that have their mParamIdx set > -1
Parameters
paramIdx The index of the parameter to be updated
value The new value of the parameter
normalized true if value is normalised
Reimplemented in IPlugWAM, IPlugVST3Processor, and IGraphicsDelegate.
Definition at line 109 of file IPlugDelegate.h.
References OnParamChangeUI().
Referenced by IGraphicsDelegate::SendParameterValueToUIFromDelegate().
virtual void IDelegate::SetControlValueFromDelegate (int controlTag, double normalizedValue) inline virtual
In IGraphics plug-ins, this method is used to update IControls in the user interface from the plug-in class, when the control is not linked to a parameter, for example a typical use case would be a meter control.
It is called by the IPlug "user" a.k.a you - not by an API class. In OnIdle() your plug-in would call this method to update the IControl's value. YOU SHOULD NOT CALL THIS ON THE AUDIO THREAD! If you are not using IGraphics, you could use it in a similar way, as long as your control/meter has a unique tag
Parameters
controlTag A tag for the control
normalizedValue The normalised value to set the control to. This will modify IControl::mValue;
Reimplemented in IPlugWAM, IPlugVST3Processor, and IGraphicsDelegate.
Definition at line 96 of file IPlugDelegate.h.
virtual void IDelegate::SetParameterValueFromUI (int paramIdx, double normalizedValue) inline virtual
Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
Parameters
paramIdx The index of the parameter that is changing value
value The new normalised value of the parameter
Reimplemented in IPlugBase, and IPlugWeb.
Definition at line 125 of file IPlugDelegate.h.
References GetParam(), NParams(), and OnParamChangeUI().
Referenced by IControl::SetAllAuxParamsFromGUI(), and IPlugBase::SetParameterValueFromUI().
Member Data Documentation
WDL_PtrList<IParam> IDelegate::mParams protected
A list of IParam objects.
This list is populated in the delegate constructor depending on the number of parameters passed as an argument to IPLUG_CTOR in the plug-in class implementation constructor
Definition at line 152 of file IPlugDelegate.h.
Referenced by GetParam(), NParams(), IPlugBase::OnParamReset(), IGraphicsDelegate::OnRestoreState(), IPluginDelegate::SerializeParams(), and IPluginDelegate::UnserializeParams().
The documentation for this class was generated from the following file:
IPlugDelegate.h