WDL-OL/IPlug: IPlugBase Class Reference
IPlugBase Class Reference
The base class of an IPlug plug-in, which interacts with the different plug-in APIs.
#include <IPlugBase.h>
Classes
struct ParamChange
Public Member Functions
IPlugBase (IPlugConfig config, EAPI plugAPI)
virtual bool CompareState (const uint8_t *pIncomingState, int startPos)
Override this method to implement a custom comparison of incoming state data with your plug-ins state data, in order to support the ProTools compare light when using custom state chunks.
virtual void OnUIOpen ()
Override this method to be notified when the UI is opened.
virtual void OnUIClose ()
Override this method to be notified when the UI is closed.
virtual void OnWindowResize ()
Implement this to do something after the user interface is resized.
virtual void OnHostRequestingAboutBox ()
virtual void OnHostRequestingProductHelp ()
virtual void OnHostIdentified ()
Implement this to do something specific when IPlug becomes aware of the particular host that is hosting the plug-in.
virtual void OnHostRequestingImportantParameters (int count, WDL_TypedBuf< int > &results)
Called by AUv3 plug-ins to get the "overview parameters".
virtual bool OnHostRequestingSupportedViewConfiguration (int width, int height)
Called by AUv3 plug-in hosts to query support for multiple UI sizes.
virtual void OnHostSelectedViewConfiguration (int width, int height)
Called by some AUv3 plug-in hosts when a particular UI size is selected.
virtual bool GetMidiNoteText (int noteNumber, char *str) const
Override this method to provide custom text linked to MIDI note numbers in API classes that support that (VST2) Typically this might be used for a drum machine plug-in, in order to label a certainty "kick drum" etc.
virtual void * GetAAXViewInterface ()
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
virtual void OnIdle ()
Override this method to get an "idle"" call on the main thread.
virtual void PrintDebugInfo () const
Helper method, used to print some info to the console in debug builds.
void DirtyParameters ()
This method will loop through all parameters, telling the host that they changed.
virtual void ResizeGraphics ()
Call this method in order to notify the API of a graphics resize.
virtual void BeginInformHostOfParamChange (int paramIdx)
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
virtual void EndInformHostOfParamChange (int paramIdx)
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
void SetParameterValue (int paramIdx, double normalizedValue)
SetParameterValue is called from the UI in the middle of a parameter change gesture (possibly via delegate) in order to update a parameter's value.
virtual void _SendParameterValueToUIFromAPI (int paramIdx, double value, bool normalized)
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange() NOTE: It may be called on the high priority audio thread.
void SetHost (const char *host, int version)
Called to set the name of the current host, if known.
virtual void HostSpecificInit ()
This method is called by some API classes, in order to do specific initialisation for particular problematic hosts.
void OnParamReset (EParamSource source)
Calls OnParamChange() for each parameter and finally OnReset().
void SetParameterValueFromUI (int paramIdx, double value) override
Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
void BeginInformHostOfParamChangeFromUI (int paramIdx) override
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void EndInformHostOfParamChangeFromUI (int paramIdx) override
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void SendMidiMsgFromUI (const IMidiMsg &msg) override
When we want to send a MIDI message from the UI for example clicking on a key in a virtual keyboard, this method should be used.
void SendSysexMsgFromUI (int size, const uint8_t *pData) override
void SendMsgFromUI (const char *msgID, int dataSize=0, const void *pData=nullptr) override
void CreateTimer ()
Public Member Functions inherited from IPluginDelegate
IPluginDelegate (int nParams, int nPresets)
const char * GetPluginName () const
int GetPluginVersion (bool decimal) const
Get the plug-in version number.
void GetPluginVersionStr (WDL_String &str) const
Gets the plug-in version as a string.
const char * GetMfrName () const
Get the manufacturer name as a CString.
const char * GetProductName () const
Get the product name as a CString.
int GetUniqueID () const
int GetMfrID () const
virtual EHost GetHost ()
int GetHostVersion (bool decimal)
Get the host version number as an integer.
void GetHostVersionStr (WDL_String &str)
Get the host version number as a string.
EAPI GetAPI () const
const char * GetAPIStr () const
const char * GetArchStr () const
void GetBuildInfoStr (WDL_String &str) const
Used to get the build date of the plug-in and architecture/api details in one string.
bool HasUI () const
int Width () const
int Height () const
int NParamGroups ()
int AddParamGroup (const char *name)
Called to add a parameter group name, when a unique group name is discovered.
const char * GetParamGroupName (int idx)
Get the parameter group name as a particular index.
virtual void InformHostOfParameterDetailsChange ()
Implemented by the API class, call this if you update parameter labels and hopefully the host should update it's displays (not applicable to all APIs)
virtual void OnParamChange (int paramIdx, EParamSource source, int sampleOffset=-1)
Override this method to do something when a parameter changes.
virtual void OnParamChange (int paramIdx)
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
bool DoesStateChunks () const
bool SerializeParams (IByteChunk &chunk)
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
int UnserializeParams (const IByteChunk &chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
virtual bool SerializeState (IByteChunk &chunk)
Override this method to serialize custom state data, if your plugin does state chunks.
virtual int UnserializeState (const IByteChunk &chunk, int startPos)
Override this method to unserialize custom state data, if your plugin does state chunks.
int GetCurrentPresetIdx () const
Get the index of the current, active preset.
void SetCurrentPresetIdx (int idx)
Set the index of the current, active preset.
virtual void InformHostOfProgramChange ()
Implemented by the API class, called by the UI (etc) when the plug-in initiates a program/preset change (not applicable to all APIs)
void ModifyCurrentPreset (const char *name=0)
int NPresets ()
bool RestorePreset (int idx)
bool RestorePreset (const char *name)
const char * GetPresetName (int idx)
void MakeDefaultPreset (const char *name=0, int nPresets=1)
void MakePreset (const char *name,...)
void MakePresetFromNamedParams (const char *name, int nParamsNamed,...)
void MakePresetFromChunk (const char *name, IByteChunk &chunk)
void MakePresetFromBlob (const char *name, const char *blob, int sizeOfChunk)
void PruneUninitializedPresets ()
virtual void OnPresetsModified ()
void EnsureDefaultPreset ()
bool SerializePresets (IByteChunk &chunk)
int UnserializePresets (IByteChunk &chunk, int startPos)
void DumpPresetSrcCode (const char *file, const char *paramEnumNames[])
void DumpPresetBlob (const char *file)
void DumpAllPresetsBlob (const char *filename)
void DumpBankBlob (const char *file)
bool SaveProgramAsFXP (const char *file)
bool SaveBankAsFXB (const char *file)
bool LoadProgramFromFXP (const char *file)
bool LoadBankFromFXB (const char *file)
bool SaveBankAsFXPs (const char *path)
bool SaveProgramAsVSTPreset (const char *file)
bool LoadProgramFromVSTPreset (const char *file)
bool SaveBankAsVSTPresets (const char *path)
bool SaveProgramAsAUPreset (const char *name, const char *file)
bool LoadProgramFromAUPreset (const char *file)
bool SaveBankAsAUPresets (const char *path)
bool SaveProgramAsProToolsPreset (const char *presetName, const char *file, unsigned long pluginID)
bool LoadProgramFromProToolsPreset (const char *file)
bool SaveBankAsProToolsPresets (const char *bath, unsigned long pluginID)
void InitFromDelegate (IPluginDelegate &delegate)
Initialise this delegate from another one.
void InitParamRange (int startIdx, int endIdx, int countStart, const char *nameFmtStr, double defaultVal, double minVal, double maxVal, double step, const char *label="", int flags=0, const char *group="", IParam::Shape *shape=nullptr, IParam::EParamUnit unit=IParam::kUnitCustom, IParam::DisplayFunc displayFunc=nullptr)
Initialise a range of parameters simultaneously.
void CloneParamRange (int cloneStartIdx, int cloneEndIdx, int startIdx, const char *searchStr="", const char *replaceStr="", const char *newGroup="")
Clone a range of parameters, optionally doing a string substitution on the parameter name.
void ForParamInRange (int startIdx, int endIdx, std::function< void(int paramIdx, IParam &param)> func)
Modify a range of parameters with a lamda function.
void ForParamInGroup (const char *paramGroup, std::function< void(int paramIdx, IParam &param)> func)
Modify a parameter group simulataneously.
void CopyParamValues (int startIdx, int destIdx, int nParams)
Copy a range of parameter values.
void CopyParamValues (const char *inGroup, const char *outGroup)
Copy a range of parameter values for a parameter group.
void RandomiseParamValues (int startIdx, int endIdx)
Randomise parameter values within a range.
void RandomiseParamValues (const char *paramGroup)
Randomise parameter values for a parameter group.
void DefaultParamValues (int startIdx, int endIdx)
Default parameter values within a range.
void DefaultParamValues (const char *paramGroup)
Default parameter values for a parameter group.
Public Member Functions inherited from IDelegate
IDelegate (int nParams)
IParam * GetParam (int paramIdx)
Get a pointer to one of the delegate's IParam objects.
int NParams () const
virtual void * OpenWindow (void *pHandle)
Override this method when not using IGraphics in order to return a platform view handle e.g.
virtual void CloseWindow ()
Override this method when not using IGraphics if you need to free resources etc when the window closes.
virtual void OnParamChangeUI (int paramIdx)
This is an OnParamChange that will only trigger on the UI thread at low priority, and therefore is appropriate for hiding or showing elements of the UI.
virtual void OnMidiMsgUI (const IMidiMsg &msg)
virtual void OnSysexMsgUI (int size, const void *pData)
virtual bool OnMessage (const char *msgID, int dataSize, const void *pData)
This could be implemented in either DSP or EDITOR to receive a message from the other one.
virtual void OnRestoreState ()
This is called by API classes after restoring state and by IPluginDelegate::RestorePreset().
virtual void SetControlValueFromDelegate (int controlTag, double normalizedValue)
In IGraphics plug-ins, this method is used to update IControls in the user interface from the plug-in class, when the control is not linked to a parameter, for example a typical use case would be a meter control.
virtual void SendControlMsgFromDelegate (int controlTag, int messageTag, int dataSize, const void *pData)
virtual void SendMsgFromDelegate (const char *msg, int dataSize, const void *pData)
virtual void SendParameterValueToUIFromDelegate (int paramIdx, double value, bool normalized)
This method is called by the class implementing DELEGATE, NOT THE PLUGIN API class in order to update the user interface with the new parameter values, typically after automation.
virtual void ResizeGraphicsFromUI ()
Sometimes when a plug-in wants to change its UI dimensions we need to call into the plug-in api class first when we click a button in our UI This method is implemented in various classes that inherit this interface to implement that behaviour.
Public Attributes
IPlugQueue< ParamChange > mParamChangeToUIQueue
IPlugQueue< IMidiMsg > mMidiMsgsFromController {32}
IPlugQueue< IMidiMsg > mMidiMsgsFromProcessor {32}
WDL_String mParamDisplayStr
Timer * mTimer = nullptr
Additional Inherited Members
Protected Attributes inherited from IPluginDelegate
int mCurrentPresetIdx = 0
bool mStateChunks = false
true if the plug-in does opaque state chunks.
WDL_String mPluginName
The name of this plug-in.
WDL_String mProductName
Product name: if the plug-in is part of collection of plug-ins it might be one product.
WDL_String mMfrName
Plug-in Manufacturer name.
int mUniqueID
int mMfrID
int mVersion
Plug-in version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
int mHostVersion = 0
Host version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
EHost mHost = kHostUninit
Host that has been identified, see EHost enum.
EAPI mAPI
API of this instance.
bool mHasUI = false
true if the plug-in has a user interface.
int mWidth = 0
The default width of the plug-in UI if it has an interface.
int mHeight = 0
The default height of the plug-in UI if it has an interface.
WDL_PtrList< const char > mParamGroups
A list of unique cstrings found specified as "parameter groups" when defining IParams.
WDL_PtrList< IPreset > mPresets
WDL_Mutex mParams_mutex
Lock when accessing mParams (including via GetParam) from the audio thread.
Protected Attributes inherited from IDelegate
WDL_PtrList< IParam > mParams
A list of IParam objects.
Detailed Description
The base class of an IPlug plug-in, which interacts with the different plug-in APIs.
No UI framework code here. This interface does not handle audio processing, see
Definition at line 28 of file IPlugBase.h.
Class Documentation
struct IPlugBase::ParamChange
Definition at line 172 of file IPlugBase.h.
Class Members
bool normalized
int paramIdx
double value
Member Function Documentation
void IPlugBase::_SendParameterValueToUIFromAPI (int paramIdx, double value, bool normalized) virtual
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange() NOTE: It may be called on the high priority audio thread.
Its purpose is to place parameter changes in a queue to defer to main thread for the UI
Parameters
paramIdx The index of the parameter that changed
value The new value
normalized /true if value is normalised
Definition at line 119 of file IPlugBase.cpp.
virtual void IPlugBase::BeginInformHostOfParamChange (int paramIdx) inline virtual
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Reimplemented in IPlugAAX, IPlugVST3Controller, IPlugAU, IPlugAPP, IPlugVST3, and IPlugVST2.
Definition at line 114 of file IPlugBase.h.
Referenced by BeginInformHostOfParamChangeFromUI().
void IPlugBase::BeginInformHostOfParamChangeFromUI (int paramIdx) inline override virtual
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
Parameters
paramIdx The index of the parameter that is changing value
Implements IDelegate.
Definition at line 150 of file IPlugBase.h.
References BeginInformHostOfParamChange().
bool IPlugBase::CompareState (const uint8_t * pIncomingState, int startPos) virtual
Override this method to implement a custom comparison of incoming state data with your plug-ins state data, in order to support the ProTools compare light when using custom state chunks.
The default implementation will compare the serialized parameters.
Parameters
pIncomingState The incoming state data
startPos The position to start in the incoming data in bytes
Returns
true in order to indicate that the states are equal.
Definition at line 54 of file IPlugBase.cpp.
References IDelegate::GetParam(), IDelegate::NParams(), and IParam::Value().
void IPlugBase::DirtyParameters ()
This method will loop through all parameters, telling the host that they changed.
You can use it if you restore a preset using a custom preset mechanism.
Definition at line 110 of file IPlugBase.cpp.
References IDelegate::GetParam(), and IDelegate::NParams().
virtual void IPlugBase::EndInformHostOfParamChange (int paramIdx) inline virtual
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Reimplemented in IPlugAAX, IPlugVST3Controller, IPlugAU, IPlugAPP, IPlugVST3, and IPlugVST2.
Definition at line 118 of file IPlugBase.h.
Referenced by EndInformHostOfParamChangeFromUI().
void IPlugBase::EndInformHostOfParamChangeFromUI (int paramIdx) inline override virtual
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
Parameters
paramIdx The index of the parameter that is changing value
Implements IDelegate.
Definition at line 151 of file IPlugBase.h.
References EndInformHostOfParamChange().
virtual void* IPlugBase::GetAAXViewInterface () inline virtual
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
Returns
pointer to the class that implements the IAAXViewInterface
Definition at line 90 of file IPlugBase.h.
virtual bool IPlugBase::GetMidiNoteText (int noteNumber, char * str) const inline virtual
Override this method to provide custom text linked to MIDI note numbers in API classes that support that (VST2) Typically this might be used for a drum machine plug-in, in order to label a certainty "kick drum" etc.
Parameters
noteNumber MIDI note to get the textual description for
str char array to set the text for the note. Should be less thatn kVstMaxNameLen (64) characters
Returns
true if you specified a custom textual description for this note
Definition at line 85 of file IPlugBase.h.
virtual void IPlugBase::HostSpecificInit () inline virtual
This method is called by some API classes, in order to do specific initialisation for particular problematic hosts.
This is not the same as OnHostIdentified(), which you may implement in your plug-in class to do your own specific initialisation after a host has been identified
Reimplemented in IPlugAU, and IPlugVST2.
Definition at line 142 of file IPlugBase.h.
virtual void IPlugBase::OnHostIdentified () inline virtual
Implement this to do something specific when IPlug becomes aware of the particular host that is hosting the plug-in.
The method may get called multiple times.
Definition at line 62 of file IPlugBase.h.
Referenced by IPlugVST2::HostSpecificInit().
void IPlugBase::OnHostRequestingImportantParameters (int count, WDL_TypedBuf< int > & results) virtual
Called by AUv3 plug-ins to get the "overview parameters".
Parameters
count How many overview parameters
results You should populate this typed buf with the indexes of the overview parameters if the host wants to show count number of controls
Definition at line 43 of file IPlugBase.cpp.
virtual bool IPlugBase::OnHostRequestingSupportedViewConfiguration (int width, int height) inline virtual
Called by AUv3 plug-in hosts to query support for multiple UI sizes.
Parameters
width The width the host offers
height The height the host offers
Returns
return true if your plug-in supports these dimensions
Definition at line 73 of file IPlugBase.h.
virtual void IPlugBase::OnHostSelectedViewConfiguration (int width, int height) inline virtual
Called by some AUv3 plug-in hosts when a particular UI size is selected.
Parameters
width The selected width
height The selected height
Definition at line 78 of file IPlugBase.h.
void IPlugBase::OnParamReset (EParamSource source)
Calls OnParamChange() for each parameter and finally OnReset().
Parameters
source Specifies the source of this parameter change
Definition at line 102 of file IPlugBase.cpp.
References IDelegate::mParams, and IPluginDelegate::OnParamChange().
virtual void IPlugBase::OnUIClose () inline virtual
Override this method to be notified when the UI is closed.
Definition at line 49 of file IPlugBase.h.
virtual void IPlugBase::OnUIOpen () inline virtual
Override this method to be notified when the UI is opened.
Definition at line 46 of file IPlugBase.h.
void IPlugBase::PrintDebugInfo () const virtual
Helper method, used to print some info to the console in debug builds.
Can be overridden in other IPlugBases, for specific functionality, such as printing UI details.
Definition at line 75 of file IPlugBase.cpp.
References IPluginDelegate::GetBuildInfoStr().
virtual void IPlugBase::ResizeGraphics () inline virtual
Call this method in order to notify the API of a graphics resize.
Reimplemented in IPlugAAX, IPlugVST3Controller, IPlugAU, IPlugVST3, IPlugAPP, and IPlugVST2.
Definition at line 110 of file IPlugBase.h.
void IPlugBase::SendMidiMsgFromUI (const IMidiMsg & msg) override virtual
When we want to send a MIDI message from the UI for example clicking on a key in a virtual keyboard, this method should be used.
Parameters
status The status byte of the MIDI message
data1 The first data byte of the MIDI message
data2 The second data byte of the MIDI message
Reimplemented from IDelegate.
Reimplemented in IPlugVST3Controller.
Definition at line 156 of file IPlugBase.cpp.
void IPlugBase::SetHost (const char * host, int version)
Called to set the name of the current host, if known.
Parameters
host The name of the plug-in host
version The version of the plug-in host where version in hex = 0xVVVVRRMM
Definition at line 84 of file IPlugBase.cpp.
References LookUpHost(), IPluginDelegate::mHost, and IPluginDelegate::mHostVersion.
Referenced by IPlugVST2::GetHost().
void IPlugBase::SetParameterValue (int paramIdx, double normalizedValue)
SetParameterValue is called from the UI in the middle of a parameter change gesture (possibly via delegate) in order to update a parameter's value.
It will update mParams[paramIdx], call InformHostOfParamChange and IPlugBase::OnParamChange();
Parameters
paramIdx The index of the parameter that changed
normalizedValue The new (normalised) value
Definition at line 94 of file IPlugBase.cpp.
References IDelegate::GetParam(), and IPluginDelegate::OnParamChange().
Referenced by SetParameterValueFromUI().
void IPlugBase::SetParameterValueFromUI (int paramIdx, double normalizedValue) inline override virtual
Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
Parameters
paramIdx The index of the parameter that is changing value
value The new normalised value of the parameter
Reimplemented from IDelegate.
Reimplemented in IPlugWeb.
Definition at line 149 of file IPlugBase.h.
References SetParameterValue(), and IDelegate::SetParameterValueFromUI().
Referenced by IPlugWeb::SetParameterValueFromUI().
The documentation for this class was generated from the following files:
IPlugBase.h
IPlugBase.cpp