WDL-OL/IPlug: IPluginDelegate Class Reference
IPluginDelegate Class Reference
This TODO has methods for serialization of state It provides a base interface for remote editors as well as the main plug-in, because we may have state/preset management in remote editors, depending on the arrangement/separation we have chosen It needn't be a "plug-in" that implements this interface, it can also be used for other things An example use case: you would like to pop up a custom preferences window with a few simple checkboxes.
#include <IPlugPluginDelegate.h>
Public Member Functions
IPluginDelegate (int nParams, int nPresets)
const char * GetPluginName () const
int GetPluginVersion (bool decimal) const
Get the plug-in version number.
void GetPluginVersionStr (WDL_String &str) const
Gets the plug-in version as a string.
const char * GetMfrName () const
Get the manufacturer name as a CString.
const char * GetProductName () const
Get the product name as a CString.
int GetUniqueID () const
int GetMfrID () const
virtual EHost GetHost ()
int GetHostVersion (bool decimal)
Get the host version number as an integer.
void GetHostVersionStr (WDL_String &str)
Get the host version number as a string.
EAPI GetAPI () const
const char * GetAPIStr () const
const char * GetArchStr () const
void GetBuildInfoStr (WDL_String &str) const
Used to get the build date of the plug-in and architecture/api details in one string.
bool HasUI () const
int Width () const
int Height () const
int NParamGroups ()
int AddParamGroup (const char *name)
Called to add a parameter group name, when a unique group name is discovered.
const char * GetParamGroupName (int idx)
Get the parameter group name as a particular index.
virtual void InformHostOfParameterDetailsChange ()
Implemented by the API class, call this if you update parameter labels and hopefully the host should update it's displays (not applicable to all APIs)
virtual void OnParamChange (int paramIdx, EParamSource source, int sampleOffset=-1)
Override this method to do something when a parameter changes.
virtual void OnParamChange (int paramIdx)
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
bool DoesStateChunks () const
bool SerializeParams (IByteChunk &chunk)
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
int UnserializeParams (const IByteChunk &chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
virtual bool SerializeState (IByteChunk &chunk)
Override this method to serialize custom state data, if your plugin does state chunks.
virtual int UnserializeState (const IByteChunk &chunk, int startPos)
Override this method to unserialize custom state data, if your plugin does state chunks.
int GetCurrentPresetIdx () const
Get the index of the current, active preset.
void SetCurrentPresetIdx (int idx)
Set the index of the current, active preset.
virtual void InformHostOfProgramChange ()
Implemented by the API class, called by the UI (etc) when the plug-in initiates a program/preset change (not applicable to all APIs)
void ModifyCurrentPreset (const char *name=0)
int NPresets ()
bool RestorePreset (int idx)
bool RestorePreset (const char *name)
const char * GetPresetName (int idx)
void MakeDefaultPreset (const char *name=0, int nPresets=1)
void MakePreset (const char *name,...)
void MakePresetFromNamedParams (const char *name, int nParamsNamed,...)
void MakePresetFromChunk (const char *name, IByteChunk &chunk)
void MakePresetFromBlob (const char *name, const char *blob, int sizeOfChunk)
void PruneUninitializedPresets ()
virtual void OnPresetsModified ()
void EnsureDefaultPreset ()
bool SerializePresets (IByteChunk &chunk)
int UnserializePresets (IByteChunk &chunk, int startPos)
void DumpPresetSrcCode (const char *file, const char *paramEnumNames[])
void DumpPresetBlob (const char *file)
void DumpAllPresetsBlob (const char *filename)
void DumpBankBlob (const char *file)
bool SaveProgramAsFXP (const char *file)
bool SaveBankAsFXB (const char *file)
bool LoadProgramFromFXP (const char *file)
bool LoadBankFromFXB (const char *file)
bool SaveBankAsFXPs (const char *path)
bool SaveProgramAsVSTPreset (const char *file)
bool LoadProgramFromVSTPreset (const char *file)
bool SaveBankAsVSTPresets (const char *path)
bool SaveProgramAsAUPreset (const char *name, const char *file)
bool LoadProgramFromAUPreset (const char *file)
bool SaveBankAsAUPresets (const char *path)
bool SaveProgramAsProToolsPreset (const char *presetName, const char *file, unsigned long pluginID)
bool LoadProgramFromProToolsPreset (const char *file)
bool SaveBankAsProToolsPresets (const char *bath, unsigned long pluginID)
void InitFromDelegate (IPluginDelegate &delegate)
Initialise this delegate from another one.
void InitParamRange (int startIdx, int endIdx, int countStart, const char *nameFmtStr, double defaultVal, double minVal, double maxVal, double step, const char *label="", int flags=0, const char *group="", IParam::Shape *shape=nullptr, IParam::EParamUnit unit=IParam::kUnitCustom, IParam::DisplayFunc displayFunc=nullptr)
Initialise a range of parameters simultaneously.
void CloneParamRange (int cloneStartIdx, int cloneEndIdx, int startIdx, const char *searchStr="", const char *replaceStr="", const char *newGroup="")
Clone a range of parameters, optionally doing a string substitution on the parameter name.
void ForParamInRange (int startIdx, int endIdx, std::function< void(int paramIdx, IParam &param)> func)
Modify a range of parameters with a lamda function.
void ForParamInGroup (const char *paramGroup, std::function< void(int paramIdx, IParam &param)> func)
Modify a parameter group simulataneously.
void CopyParamValues (int startIdx, int destIdx, int nParams)
Copy a range of parameter values.
void CopyParamValues (const char *inGroup, const char *outGroup)
Copy a range of parameter values for a parameter group.
void RandomiseParamValues (int startIdx, int endIdx)
Randomise parameter values within a range.
void RandomiseParamValues (const char *paramGroup)
Randomise parameter values for a parameter group.
void DefaultParamValues (int startIdx, int endIdx)
Default parameter values within a range.
void DefaultParamValues (const char *paramGroup)
Default parameter values for a parameter group.
Public Member Functions inherited from IDelegate
IDelegate (int nParams)
IParam * GetParam (int paramIdx)
Get a pointer to one of the delegate's IParam objects.
int NParams () const
virtual void * OpenWindow (void *pHandle)
Override this method when not using IGraphics in order to return a platform view handle e.g.
virtual void CloseWindow ()
Override this method when not using IGraphics if you need to free resources etc when the window closes.
virtual void OnParamChangeUI (int paramIdx)
This is an OnParamChange that will only trigger on the UI thread at low priority, and therefore is appropriate for hiding or showing elements of the UI.
virtual void OnMidiMsgUI (const IMidiMsg &msg)
virtual void OnSysexMsgUI (int size, const void *pData)
virtual bool OnMessage (const char *msgID, int dataSize, const void *pData)
This could be implemented in either DSP or EDITOR to receive a message from the other one.
virtual void OnRestoreState ()
This is called by API classes after restoring state and by IPluginDelegate::RestorePreset().
virtual void SetControlValueFromDelegate (int controlTag, double normalizedValue)
In IGraphics plug-ins, this method is used to update IControls in the user interface from the plug-in class, when the control is not linked to a parameter, for example a typical use case would be a meter control.
virtual void SendControlMsgFromDelegate (int controlTag, int messageTag, int dataSize, const void *pData)
virtual void SendMsgFromDelegate (const char *msg, int dataSize, const void *pData)
virtual void SendParameterValueToUIFromDelegate (int paramIdx, double value, bool normalized)
This method is called by the class implementing DELEGATE, NOT THE PLUGIN API class in order to update the user interface with the new parameter values, typically after automation.
virtual void BeginInformHostOfParamChangeFromUI (int paramIdx)=0
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
virtual void SetParameterValueFromUI (int paramIdx, double normalizedValue)
Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
virtual void EndInformHostOfParamChangeFromUI (int paramIdx)=0
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
virtual void ResizeGraphicsFromUI ()
Sometimes when a plug-in wants to change its UI dimensions we need to call into the plug-in api class first when we click a button in our UI This method is implemented in various classes that inherit this interface to implement that behaviour.
virtual void SendMidiMsgFromUI (const IMidiMsg &msg)
When we want to send a MIDI message from the UI for example clicking on a key in a virtual keyboard, this method should be used.
virtual void SendSysexMsgFromUI (int size, const uint8_t *pData)
virtual void SendMsgFromUI (const char *msgID, int dataSize=0, const void *pData=nullptr)
Protected Attributes
int mCurrentPresetIdx = 0
bool mStateChunks = false
true if the plug-in does opaque state chunks.
WDL_String mPluginName
The name of this plug-in.
WDL_String mProductName
Product name: if the plug-in is part of collection of plug-ins it might be one product.
WDL_String mMfrName
Plug-in Manufacturer name.
int mUniqueID
int mMfrID
int mVersion
Plug-in version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
int mHostVersion = 0
Host version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
EHost mHost = kHostUninit
Host that has been identified, see EHost enum.
EAPI mAPI
API of this instance.
bool mHasUI = false
true if the plug-in has a user interface.
int mWidth = 0
The default width of the plug-in UI if it has an interface.
int mHeight = 0
The default height of the plug-in UI if it has an interface.
WDL_PtrList< const char > mParamGroups
A list of unique cstrings found specified as "parameter groups" when defining IParams.
WDL_PtrList< IPreset > mPresets
WDL_Mutex mParams_mutex
Lock when accessing mParams (including via GetParam) from the audio thread.
Protected Attributes inherited from IDelegate
WDL_PtrList< IParam > mParams
A list of IParam objects.
Detailed Description
This TODO has methods for serialization of state It provides a base interface for remote editors as well as the main plug-in, because we may have state/preset management in remote editors, depending on the arrangement/separation we have chosen It needn't be a "plug-in" that implements this interface, it can also be used for other things An example use case: you would like to pop up a custom preferences window with a few simple checkboxes.
You should be able to do that with a new graphics context and something implementing this interface in order to send/receive values to/from your new UI.
Note on method names: "FromUI" in a method name, means that that method is called by the UI class. Likewise "ToUI" means that the method is delivering something wait for it... to the UI. The words "FromDelegate" in a method name mean that method is called from the class that implements the IDelegate interface, which is usually your plug-in base class. A parameter value is a floating point number linked to an integer parameter index. A parameter object is an instance of the IParam class as defined in IPlugParameter.h, owned by IPlugBase. A parameter object is also referred to as a "param", in method names such as IPlugBase::GetParam(int paramIdx) and IControl::GetParam().
Definition at line 24 of file IPlugPluginDelegate.h.
Member Function Documentation
int IPluginDelegate::AddParamGroup (const char * name) inline
Called to add a parameter group name, when a unique group name is discovered.
Parameters
name CString for the unique group name
Returns
Number of parameter groups
Definition at line 101 of file IPlugPluginDelegate.h.
References mParamGroups, and NParamGroups().
void IPluginDelegate::CloneParamRange (int cloneStartIdx, int cloneEndIdx, int startIdx, const char * searchStr = "", const char * replaceStr = "", const char * newGroup = "")
Clone a range of parameters, optionally doing a string substitution on the parameter name.
Parameters
cloneStartIdx The index of the first parameter to clone
cloneEndIdx The index of the last parameter to clone
startIdx The start of the cloned range
searchStr A CString to search for in the input parameter name
replaceStr A CString to replace searchStr in the output parameter name
newGroup If the new parameter should have a different group, update here
Definition at line 148 of file IPlugPluginDelegate.cpp.
References IDelegate::GetParam(), IParam::Set(), and IParam::Value().
void IPluginDelegate::CopyParamValues (int startIdx, int destIdx, int nParams)
Copy a range of parameter values.
Parameters
startIdx The index of the first parameter value to copy
destIdx The index of the first destination parameter
nParams The number of parameters to copy
Definition at line 159 of file IPlugPluginDelegate.cpp.
References IDelegate::GetParam(), IDelegate::NParams(), and IParam::Set().
void IPluginDelegate::CopyParamValues (const char * inGroup, const char * outGroup)
Copy a range of parameter values for a parameter group.
Parameters
inGroup The name of the group to copy from
outGroup The name of the group to copy to
Definition at line 171 of file IPlugPluginDelegate.cpp.
References IDelegate::GetParam(), and IDelegate::NParams().
void IPluginDelegate::DefaultParamValues (int startIdx, int endIdx)
Default parameter values within a range.
Parameters
startIdx The index of the first parameter to modify
endIdx The index of the last parameter to modify
Definition at line 216 of file IPlugPluginDelegate.cpp.
References ForParamInRange().
void IPluginDelegate::DefaultParamValues (const char * paramGroup)
Default parameter values for a parameter group.
Parameters
paramGroup The name of the group to modify
Definition at line 223 of file IPlugPluginDelegate.cpp.
References ForParamInGroup().
bool IPluginDelegate::DoesStateChunks () const inline
Returns
true if the plug-in has been set up to do state chunks, via config.h
Definition at line 125 of file IPlugPluginDelegate.h.
References mStateChunks.
void IPluginDelegate::ForParamInGroup (const char * paramGroup, std::function< void(int paramIdx, IParam &param)> func)
Modify a parameter group simulataneously.
Parameters
paramGroup The name of the group to modify
param func A lambda function to modify the parameter. Ideas: you could randomise the parameter value or reset to default
Definition at line 204 of file IPlugPluginDelegate.cpp.
References IDelegate::GetParam(), and IDelegate::NParams().
Referenced by DefaultParamValues(), and RandomiseParamValues().
void IPluginDelegate::ForParamInRange (int startIdx, int endIdx, std::function< void(int paramIdx, IParam &param)> func)
Modify a range of parameters with a lamda function.
Parameters
startIdx The index of the first parameter to modify
endIdx The index of the last parameter to modify
func A lambda function to modify the parameter. Ideas: you could randomise the parameter value or reset to default, modify certain params based on their group
Definition at line 196 of file IPlugPluginDelegate.cpp.
References IDelegate::GetParam().
Referenced by DefaultParamValues(), and RandomiseParamValues().
EAPI IPluginDelegate::GetAPI () const inline
Returns
The The plug-in API, see EAPI enum for a list of possible APIs
Definition at line 71 of file IPlugPluginDelegate.h.
References mAPI.
Referenced by GetAPIStr().
const char * IPluginDelegate::GetAPIStr () const
Returns
Returns a CString describing the plug-in API, e.g. "VST2"
Definition at line 56 of file IPlugPluginDelegate.cpp.
References GetAPI().
Referenced by GetBuildInfoStr().
const char * IPluginDelegate::GetArchStr () const
Returns
Returns a CString either "x86" or "x64" or "WASM" describing the binary architecture
Definition at line 70 of file IPlugPluginDelegate.cpp.
Referenced by GetBuildInfoStr().
void IPluginDelegate::GetBuildInfoStr (WDL_String & str) const
Used to get the build date of the plug-in and architecture/api details in one string.
Note
since the implementation is in IPlugBase.cpp, you may want to touch that file as part of your build script to force recompilation
Parameters
str WDL_String will be set with the Plugin name, architecture, api, build date, build time
Definition at line 79 of file IPlugPluginDelegate.cpp.
References GetAPIStr(), GetArchStr(), GetPluginName(), and GetPluginVersionStr().
Referenced by IPlugBase::PrintDebugInfo().
int IPluginDelegate::GetCurrentPresetIdx () const inline
Get the index of the current, active preset.
Returns
The index of the current preset
Definition at line 152 of file IPlugPluginDelegate.h.
virtual EHost IPluginDelegate::GetHost () inline virtual
Returns
The host if it has been identified, see EHost enum for a list of possible hosts, implemented in the API class for VST2 and AUv2
Reimplemented in IPlugAU, IPlugVST2, and IPlugWeb.
Definition at line 59 of file IPlugPluginDelegate.h.
References mHost.
Referenced by IPlugVST2::GetHost(), IPlugAU::GetHost(), GetHostVersion(), and GetHostVersionStr().
int IPluginDelegate::GetHostVersion (bool decimal)
Get the host version number as an integer.
Parameters
decimal true indicates decimal format = VVVVRRMM, otherwise hexadecimal 0xVVVVRRMM.
Returns
The host version number as an integer.
Definition at line 40 of file IPlugPluginDelegate.cpp.
References GetHost(), and mHostVersion.
void IPluginDelegate::GetHostVersionStr (WDL_String & str)
Get the host version number as a string.
Parameters
str string into which to write the host version
Definition at line 50 of file IPlugPluginDelegate.cpp.
References GetHost(), and mHostVersion.
int IPluginDelegate::GetMfrID () const inline
Returns
The plug-in manufacturer's unique four character ID as an integer
Definition at line 56 of file IPlugPluginDelegate.h.
const char* IPluginDelegate::GetParamGroupName (int idx) inline
Get the parameter group name as a particular index.
Parameters
idx The index to return
Returns
CString for the unique group name
Definition at line 106 of file IPlugPluginDelegate.h.
References mParamGroups.
const char* IPluginDelegate::GetPluginName () const inline
Returns
the name of the plug-in as a CString
Definition at line 32 of file IPlugPluginDelegate.h.
References mPluginName.
Referenced by GetBuildInfoStr(), and IPlugWeb::SetParameterValueFromUI().
int IPluginDelegate::GetPluginVersion (bool decimal) const
Get the plug-in version number.
Parameters
decimal Sets the output format
Returns
Effect version in VVVVRRMM (if decimal is true) or Hexadecimal 0xVVVVRRMM (if decimal is false) format
Definition at line 21 of file IPlugPluginDelegate.cpp.
References mVersion.
void IPluginDelegate::GetPluginVersionStr (WDL_String & str) const
Gets the plug-in version as a string.
Parameters
str WDL_String to write to The output format is vX.M.m, where X - version, M - major, m - minor
Note
If _DEBUG is defined, D is appended to the version string
If TRACER_BUILD is defined, T is appended to the version string
Definition at line 29 of file IPlugPluginDelegate.cpp.
References mVersion.
Referenced by GetBuildInfoStr().
const char* IPluginDelegate::GetProductName () const inline
Get the product name as a CString.
A shipping product may contain multiple plug-ins, hence this. Not used in all APIs
Definition at line 50 of file IPlugPluginDelegate.h.
References mProductName.
int IPluginDelegate::GetUniqueID () const inline
Returns
The plug-in's unique four character ID as an integer
Definition at line 53 of file IPlugPluginDelegate.h.
bool IPluginDelegate::HasUI () const inline
Returns
true if the plug-in is meant to have a UI, as defined in config.h
Definition at line 85 of file IPlugPluginDelegate.h.
References mHasUI.
Referenced by IPlugVST2::ResizeGraphics(), IPlugAPP::ResizeGraphics(), IPlugVST3::ResizeGraphics(), and IPlugAAX::ResizeGraphics().
int IPluginDelegate::Height () const inline
Returns
The default height of the plug-in UI in pixels, if defined in config.h
Definition at line 91 of file IPlugPluginDelegate.h.
References mHeight.
Referenced by IPlugVST2::ResizeGraphics(), IPlugAPP::ResizeGraphics(), IPlugVST3::ResizeGraphics(), and IPlugAAX::ResizeGraphics().
void IPluginDelegate::InitFromDelegate (IPluginDelegate & delegate)
Initialise this delegate from another one.
Parameters
delegate The delegate to clone
Definition at line 128 of file IPlugPluginDelegate.cpp.
References IDelegate::GetParam(), IDelegate::NParams(), IParam::Set(), and IParam::Value().
void IPluginDelegate::InitParamRange (int startIdx, int endIdx, int countStart, const char * nameFmtStr, double defaultVal, double minVal, double maxVal, double step, const char * label = "", int flags = 0, const char * group = "", IParam::Shape * shape = nullptr, IParam::EParamUnit unit = IParam::kUnitCustom, IParam::DisplayFunc displayFunc = nullptr)
Initialise a range of parameters simultaneously.
This mirrors the arguments available in IParam::InitDouble, for maximum flexibility
Parameters
startIdx The index of the first parameter to initialise
endIdx The index of the last parameter to initialise
countStart An integer representing the start of the count in the format string. If the first parameter should have "0" in its name, set this to 0
nameFmtStr A limited format string where i can be used to get the index + countStart, in the range of parameters specified
defaultVal A default real value for the parameter
minVal A minimum real value for the parameter
maxVal A Maximum real value for the parameter
step The parameter step
label A CString label for the parameter e.g. "decibels"
flags Any flags, see IParam::EFlags
group A CString group name for the parameter, e.g. "envelope"
shape A IParam::Shape class to determine how the parameter shape should be skewed
unit An IParam::EParamUnit which can be used in audiounit plug-ins to specify certain kinds of parameter
displayFunc An IParam::DisplayFunc lambda function to specify a custom display function
Definition at line 138 of file IPlugPluginDelegate.cpp.
References IDelegate::GetParam().
int IPluginDelegate::NParamGroups () inline
Returns
The number of unique parameter groups identified
Definition at line 96 of file IPlugPluginDelegate.h.
References mParamGroups.
Referenced by AddParamGroup().
void IPluginDelegate::OnParamChange (int paramIdx, EParamSource source, int sampleOffset = -1) virtual
Override this method to do something when a parameter changes.
THIS METHOD CAN BE CALLED BY THE HIGH PRIORITY AUDIO THREAD
Parameters
paramIdx The index of the parameter that changed
source One of the EParamSource options to indicate where the parameter change came from.
sampleOffset For sample accurate parameter changes - index into current block
Definition at line 87 of file IPlugPluginDelegate.cpp.
Referenced by IPlugBase::OnParamReset(), and IPlugBase::SetParameterValue().
virtual void IPluginDelegate::OnParamChange (int paramIdx) inline virtual
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
Definition at line 121 of file IPlugPluginDelegate.h.
void IPluginDelegate::RandomiseParamValues (int startIdx, int endIdx)
Randomise parameter values within a range.
NOTE for more flexibility in terms of RNG etc, use ForParamInRange()
Parameters
startIdx The index of the first parameter to modify
endIdx The index of the last parameter to modify
Definition at line 230 of file IPlugPluginDelegate.cpp.
References ForParamInRange().
void IPluginDelegate::RandomiseParamValues (const char * paramGroup)
Randomise parameter values for a parameter group.
Parameters
paramGroup The name of the group to modify
Definition at line 241 of file IPlugPluginDelegate.cpp.
References ForParamInGroup().
bool IPluginDelegate::SerializeParams (IByteChunk & chunk)
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
Parameters
chunk The output chunk to serialize to. Will append data if the chunk has already been started.
Returns
true if the serialization was successful
Definition at line 95 of file IPlugPluginDelegate.cpp.
References IDelegate::mParams, and IParam::Value().
Referenced by SerializeState().
virtual bool IPluginDelegate::SerializeState (IByteChunk & chunk) inline virtual
Override this method to serialize custom state data, if your plugin does state chunks.
Parameters
chunk The output bytechunk where data can be serialized
Returns
true if serialization was successful
Definition at line 141 of file IPlugPluginDelegate.h.
References SerializeParams().
void IPluginDelegate::SetCurrentPresetIdx (int idx) inline
Set the index of the current, active preset.
Parameters
idx The index of the current preset
Definition at line 156 of file IPlugPluginDelegate.h.
int IPluginDelegate::UnserializeParams (const IByteChunk & chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
Parameters
chunk The incoming chunk where parameter values are stored to unserialize
startPos The start position in the chunk where parameter values are stored
Returns
The new chunk position (endPos)
Definition at line 110 of file IPlugPluginDelegate.cpp.
References IDelegate::mParams, IParam::Set(), and IParam::Value().
Referenced by UnserializeState().
virtual int IPluginDelegate::UnserializeState (const IByteChunk & chunk, int startPos) inline virtual
Override this method to unserialize custom state data, if your plugin does state chunks.
Implementations should call UnserializeParams() after custom data is unserialized
Parameters
chunk The incoming chunk containing the state data.
startPos The position in the chunk where the data starts
Returns
The new chunk position (endPos)
Definition at line 148 of file IPlugPluginDelegate.h.
References UnserializeParams().
int IPluginDelegate::Width () const inline
Returns
The default width of the plug-in UI in pixels, if defined in config.h
Definition at line 88 of file IPlugPluginDelegate.h.
References mWidth.
Referenced by IPlugVST2::ResizeGraphics(), IPlugAPP::ResizeGraphics(), IPlugVST3::ResizeGraphics(), and IPlugAAX::ResizeGraphics().
Member Data Documentation
bool IPluginDelegate::mHasUI = false protected
true if the plug-in has a user interface.
If false the host will provide a default interface
Definition at line 342 of file IPlugPluginDelegate.h.
Referenced by HasUI().
int IPluginDelegate::mHeight = 0 protected
The default height of the plug-in UI if it has an interface.
Definition at line 346 of file IPlugPluginDelegate.h.
Referenced by Height().
WDL_PtrList<const char> IPluginDelegate::mParamGroups protected
A list of unique cstrings found specified as "parameter groups" when defining IParams.
These are used in various APIs to group parameters together in automation dialogues.
Definition at line 349 of file IPlugPluginDelegate.h.
Referenced by AddParamGroup(), GetParamGroupName(), and NParamGroups().
bool IPluginDelegate::mStateChunks = false protected
true if the plug-in does opaque state chunks.
If false the host will provide a default interface
Definition at line 321 of file IPlugPluginDelegate.h.
Referenced by DoesStateChunks().
int IPluginDelegate::mWidth = 0 protected
The default width of the plug-in UI if it has an interface.
Definition at line 344 of file IPlugPluginDelegate.h.
Referenced by Width().
The documentation for this class was generated from the following files:
IPlugPluginDelegate.h
IPlugPluginDelegate.cpp