WDL-OL/IPlug: IPlugAPP Class Reference
IPlugAPP Class Reference
IPlug::APIClasses
Standalone application base class for an IPlug plug-in, inherits from IPlugBase.
#include <IPlugAPP.h>
Public Member Functions
IPlugAPP (IPlugInstanceInfo instanceInfo, IPlugConfig config)
void BeginInformHostOfParamChange (int idx) override
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
void InformHostOfParamChange (int idx, double normalizedValue) override
Implemented by the API class, called by the UI via SetParameterValue() with the value of a parameter change gesture.
void EndInformHostOfParamChange (int idx) override
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
void InformHostOfProgramChange () override
Implemented by the API class, called by the UI (etc) when the plug-in initiates a program/preset change (not applicable to all APIs)
void ResizeGraphics () override
Call this method in order to notify the API of a graphics resize.
bool SendMidiMsg (const IMidiMsg &msg) override
Send a single MIDI message.
bool SendSysEx (ISysEx &msg) override
Send a single MIDI System Exclusive (SysEx) message.
Public Member Functions inherited from IPlugBase
IPlugBase (IPlugConfig config, EAPI plugAPI)
virtual bool CompareState (const uint8_t *pIncomingState, int startPos)
Override this method to implement a custom comparison of incoming state data with your plug-ins state data, in order to support the ProTools compare light when using custom state chunks.
virtual void OnUIOpen ()
Override this method to be notified when the UI is opened.
virtual void OnUIClose ()
Override this method to be notified when the UI is closed.
virtual void OnWindowResize ()
Implement this to do something after the user interface is resized.
virtual void OnHostRequestingAboutBox ()
virtual void OnHostRequestingProductHelp ()
virtual void OnHostIdentified ()
Implement this to do something specific when IPlug becomes aware of the particular host that is hosting the plug-in.
virtual void OnHostRequestingImportantParameters (int count, WDL_TypedBuf< int > &results)
Called by AUv3 plug-ins to get the "overview parameters".
virtual bool OnHostRequestingSupportedViewConfiguration (int width, int height)
Called by AUv3 plug-in hosts to query support for multiple UI sizes.
virtual void OnHostSelectedViewConfiguration (int width, int height)
Called by some AUv3 plug-in hosts when a particular UI size is selected.
virtual bool GetMidiNoteText (int noteNumber, char *str) const
Override this method to provide custom text linked to MIDI note numbers in API classes that support that (VST2) Typically this might be used for a drum machine plug-in, in order to label a certainty "kick drum" etc.
virtual void * GetAAXViewInterface ()
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
virtual void OnIdle ()
Override this method to get an "idle"" call on the main thread.
virtual void PrintDebugInfo () const
Helper method, used to print some info to the console in debug builds.
void DirtyParameters ()
This method will loop through all parameters, telling the host that they changed.
void SetParameterValue (int paramIdx, double normalizedValue)
SetParameterValue is called from the UI in the middle of a parameter change gesture (possibly via delegate) in order to update a parameter's value.
virtual void _SendParameterValueToUIFromAPI (int paramIdx, double value, bool normalized)
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange() NOTE: It may be called on the high priority audio thread.
void SetHost (const char *host, int version)
Called to set the name of the current host, if known.
virtual void HostSpecificInit ()
This method is called by some API classes, in order to do specific initialisation for particular problematic hosts.
void OnParamReset (EParamSource source)
Calls OnParamChange() for each parameter and finally OnReset().
void SetParameterValueFromUI (int paramIdx, double value) override
Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
void BeginInformHostOfParamChangeFromUI (int paramIdx) override
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void EndInformHostOfParamChangeFromUI (int paramIdx) override
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void SendMidiMsgFromUI (const IMidiMsg &msg) override
When we want to send a MIDI message from the UI for example clicking on a key in a virtual keyboard, this method should be used.
void SendSysexMsgFromUI (int size, const uint8_t *pData) override
void SendMsgFromUI (const char *msgID, int dataSize=0, const void *pData=nullptr) override
void CreateTimer ()
Public Member Functions inherited from IPluginDelegate
IPluginDelegate (int nParams, int nPresets)
const char * GetPluginName () const
int GetPluginVersion (bool decimal) const
Get the plug-in version number.
void GetPluginVersionStr (WDL_String &str) const
Gets the plug-in version as a string.
const char * GetMfrName () const
Get the manufacturer name as a CString.
const char * GetProductName () const
Get the product name as a CString.
int GetUniqueID () const
int GetMfrID () const
virtual EHost GetHost ()
int GetHostVersion (bool decimal)
Get the host version number as an integer.
void GetHostVersionStr (WDL_String &str)
Get the host version number as a string.
EAPI GetAPI () const
const char * GetAPIStr () const
const char * GetArchStr () const
void GetBuildInfoStr (WDL_String &str) const
Used to get the build date of the plug-in and architecture/api details in one string.
bool HasUI () const
int Width () const
int Height () const
int NParamGroups ()
int AddParamGroup (const char *name)
Called to add a parameter group name, when a unique group name is discovered.
const char * GetParamGroupName (int idx)
Get the parameter group name as a particular index.
virtual void InformHostOfParameterDetailsChange ()
Implemented by the API class, call this if you update parameter labels and hopefully the host should update it's displays (not applicable to all APIs)
virtual void OnParamChange (int paramIdx, EParamSource source, int sampleOffset=-1)
Override this method to do something when a parameter changes.
virtual void OnParamChange (int paramIdx)
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
bool DoesStateChunks () const
bool SerializeParams (IByteChunk &chunk)
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
int UnserializeParams (const IByteChunk &chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
virtual bool SerializeState (IByteChunk &chunk)
Override this method to serialize custom state data, if your plugin does state chunks.
virtual int UnserializeState (const IByteChunk &chunk, int startPos)
Override this method to unserialize custom state data, if your plugin does state chunks.
int GetCurrentPresetIdx () const
Get the index of the current, active preset.
void SetCurrentPresetIdx (int idx)
Set the index of the current, active preset.
void ModifyCurrentPreset (const char *name=0)
int NPresets ()
bool RestorePreset (int idx)
bool RestorePreset (const char *name)
const char * GetPresetName (int idx)
void MakeDefaultPreset (const char *name=0, int nPresets=1)
void MakePreset (const char *name,...)
void MakePresetFromNamedParams (const char *name, int nParamsNamed,...)
void MakePresetFromChunk (const char *name, IByteChunk &chunk)
void MakePresetFromBlob (const char *name, const char *blob, int sizeOfChunk)
void PruneUninitializedPresets ()
virtual void OnPresetsModified ()
void EnsureDefaultPreset ()
bool SerializePresets (IByteChunk &chunk)
int UnserializePresets (IByteChunk &chunk, int startPos)
void DumpPresetSrcCode (const char *file, const char *paramEnumNames[])
void DumpPresetBlob (const char *file)
void DumpAllPresetsBlob (const char *filename)
void DumpBankBlob (const char *file)
bool SaveProgramAsFXP (const char *file)
bool SaveBankAsFXB (const char *file)
bool LoadProgramFromFXP (const char *file)
bool LoadBankFromFXB (const char *file)
bool SaveBankAsFXPs (const char *path)
bool SaveProgramAsVSTPreset (const char *file)
bool LoadProgramFromVSTPreset (const char *file)
bool SaveBankAsVSTPresets (const char *path)
bool SaveProgramAsAUPreset (const char *name, const char *file)
bool LoadProgramFromAUPreset (const char *file)
bool SaveBankAsAUPresets (const char *path)
bool SaveProgramAsProToolsPreset (const char *presetName, const char *file, unsigned long pluginID)
bool LoadProgramFromProToolsPreset (const char *file)
bool SaveBankAsProToolsPresets (const char *bath, unsigned long pluginID)
void InitFromDelegate (IPluginDelegate &delegate)
Initialise this delegate from another one.
void InitParamRange (int startIdx, int endIdx, int countStart, const char *nameFmtStr, double defaultVal, double minVal, double maxVal, double step, const char *label="", int flags=0, const char *group="", IParam::Shape *shape=nullptr, IParam::EParamUnit unit=IParam::kUnitCustom, IParam::DisplayFunc displayFunc=nullptr)
Initialise a range of parameters simultaneously.
void CloneParamRange (int cloneStartIdx, int cloneEndIdx, int startIdx, const char *searchStr="", const char *replaceStr="", const char *newGroup="")
Clone a range of parameters, optionally doing a string substitution on the parameter name.
void ForParamInRange (int startIdx, int endIdx, std::function< void(int paramIdx, IParam &param)> func)
Modify a range of parameters with a lamda function.
void ForParamInGroup (const char *paramGroup, std::function< void(int paramIdx, IParam &param)> func)
Modify a parameter group simulataneously.
void CopyParamValues (int startIdx, int destIdx, int nParams)
Copy a range of parameter values.
void CopyParamValues (const char *inGroup, const char *outGroup)
Copy a range of parameter values for a parameter group.
void RandomiseParamValues (int startIdx, int endIdx)
Randomise parameter values within a range.
void RandomiseParamValues (const char *paramGroup)
Randomise parameter values for a parameter group.
void DefaultParamValues (int startIdx, int endIdx)
Default parameter values within a range.
void DefaultParamValues (const char *paramGroup)
Default parameter values for a parameter group.
Public Member Functions inherited from IDelegate
IDelegate (int nParams)
IParam * GetParam (int paramIdx)
Get a pointer to one of the delegate's IParam objects.
int NParams () const
virtual void * OpenWindow (void *pHandle)
Override this method when not using IGraphics in order to return a platform view handle e.g.
virtual void CloseWindow ()
Override this method when not using IGraphics if you need to free resources etc when the window closes.
virtual void OnParamChangeUI (int paramIdx)
This is an OnParamChange that will only trigger on the UI thread at low priority, and therefore is appropriate for hiding or showing elements of the UI.
virtual void OnMidiMsgUI (const IMidiMsg &msg)
virtual void OnSysexMsgUI (int size, const void *pData)
virtual bool OnMessage (const char *msgID, int dataSize, const void *pData)
This could be implemented in either DSP or EDITOR to receive a message from the other one.
virtual void OnRestoreState ()
This is called by API classes after restoring state and by IPluginDelegate::RestorePreset().
virtual void SetControlValueFromDelegate (int controlTag, double normalizedValue)
In IGraphics plug-ins, this method is used to update IControls in the user interface from the plug-in class, when the control is not linked to a parameter, for example a typical use case would be a meter control.
virtual void SendControlMsgFromDelegate (int controlTag, int messageTag, int dataSize, const void *pData)
virtual void SendMsgFromDelegate (const char *msg, int dataSize, const void *pData)
virtual void SendParameterValueToUIFromDelegate (int paramIdx, double value, bool normalized)
This method is called by the class implementing DELEGATE, NOT THE PLUGIN API class in order to update the user interface with the new parameter values, typically after automation.
virtual void ResizeGraphicsFromUI ()
Sometimes when a plug-in wants to change its UI dimensions we need to call into the plug-in api class first when we click a button in our UI This method is implemented in various classes that inherit this interface to implement that behaviour.
Public Member Functions inherited from IPlugProcessor< PLUG_SAMPLE_DST >
IPlugProcessor (IPlugConfig config, EAPI plugAPI)
virtual void ProcessBlock (PLUG_SAMPLE_DST **inputs, PLUG_SAMPLE_DST **outputs, int nFrames)
Override in your plug-in class to process audio In ProcessBlock you are always guaranteed to get valid pointers to all the channels the plugin requested (the maximum possible input channel count and the maximum possible output channel count including multiple buses).
virtual void ProcessMidiMsg (const IMidiMsg &msg)
Override this method to handle incoming MIDI messages.
virtual void ProcessSysEx (ISysEx &msg)
Override this method to handle incoming MIDI System Exclusive (SysEx) messages.
virtual void OnReset ()
Override this method in your plug-in class to do something prior to playback etc.
virtual void OnActivate (bool active)
Override OnActivate() which should be called by the API class when a plug-in is "switched on" by the host on a track when the channel count is known.
bool SendMidiMsgs (WDL_TypedBuf< IMidiMsg > &msgs)
Send a collection of MIDI messages.
double GetSampleRate () const
int GetBlockSize () const
int GetLatency () const
int GetTailSize ()
bool GetBypassed () const
bool GetRenderingOffline () const
int GetSamplePos () const
double GetTempo () const
double GetSamplesPerBeat () const
void GetTimeSig (int &numerator, int &denominator)
int NIOConfigs () const
IOConfig * GetIOConfig (int idx)
int MaxNBuses (ERoute direction) const
Used to determine the maximum number of input or output buses based on what was specified in the channel I/O config string.
int MaxNChannelsForBus (ERoute direction, int busIdx) const
For a given input or output bus what is the maximum possible number of channels.
bool HasWildcardBus (ERoute direction) const
Check if we have any wildcard characters in the channel I/O configs.
int MaxNChannels (ERoute direction) const
bool IsChannelConnected (ERoute direction, int chIdx) const
int NChannelsConnected (ERoute direction) const
int NInChansConnected ()
Convenience method to find out how many input channels are connected.
int NOutChansConnected ()
Convenience method to find out how many output channels are connected.
bool LegalIO (int NInputChans, int NOutputChans) const
Check if a certain configuration of input channels and output channels is allowed based on the channel I/O configs.
bool HasSidechainInput () const
int NSidechainChannels () const
void LimitToStereoIO ()
This is called by IPlugVST in order to limit a plug-in to stereo I/O for certain picky hosts.
bool IsInstrument () const
bool DoesMIDI () const
void SetChannelLabel (ERoute direction, int idx, const char *formatStr, bool zeroBased=false)
This allows you to label input/output channels in supporting VST2 hosts.
virtual void SetLatency (int latency)
Call this if the latency of your plug-in changes after initialization (perhaps from OnReset()) This may not be supported by the host.
void SetTailSize (int tailSize)
Call this method if you need to update the tail size at runtime, for example if the decay time of your reverb effect changes Some apis have special interpretations of certain numbers.
void _SetSampleRate (double sampleRate)
void _SetBlockSize (int blockSize)
void _SetBypassed (bool bypassed)
void _SetTimeInfo (const ITimeInfo &timeInfo)
void _SetRenderingOffline (bool renderingOffline)
const WDL_String & _GetChannelLabel (ERoute direction, int idx)
Additional Inherited Members
Static Public Member Functions inherited from IPlugProcessor< PLUG_SAMPLE_DST >
static int ParseChannelIOStr (const char *IOStr, WDL_PtrList< IOConfig > &channelIOList, int &totalNInChans, int &totalNOutChans, int &totalNInBuses, int &totalNOutBuses)
A static method to parse the config.h channel I/O string.
Public Attributes inherited from IPlugBase
IPlugQueue< ParamChange > mParamChangeToUIQueue
IPlugQueue< IMidiMsg > mMidiMsgsFromController {32}
IPlugQueue< IMidiMsg > mMidiMsgsFromProcessor {32}
WDL_String mParamDisplayStr
Timer * mTimer = nullptr
Protected Member Functions inherited from IPlugProcessor< PLUG_SAMPLE_DST >
void _SetChannelConnections (ERoute direction, int idx, int n, bool connected)
void _AttachBuffers (ERoute direction, int idx, int n, PLUG_SAMPLE_DST **ppData, int nFrames)
void _AttachBuffers (ERoute direction, int idx, int n, PLUG_SAMPLE_SRC **ppData, int nFrames)
void _PassThroughBuffers (PLUG_SAMPLE_SRC type, int nFrames)
void _PassThroughBuffers (PLUG_SAMPLE_DST type, int nFrames)
void _ProcessBuffers (PLUG_SAMPLE_SRC type, int nFrames)
void _ProcessBuffers (PLUG_SAMPLE_DST type, int nFrames)
void _ProcessBuffersAccumulating (int nFrames)
void _ZeroScratchBuffers ()
Protected Attributes inherited from IPluginDelegate
int mCurrentPresetIdx = 0
bool mStateChunks = false
true if the plug-in does opaque state chunks.
WDL_String mPluginName
The name of this plug-in.
WDL_String mProductName
Product name: if the plug-in is part of collection of plug-ins it might be one product.
WDL_String mMfrName
Plug-in Manufacturer name.
int mUniqueID
int mMfrID
int mVersion
Plug-in version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
int mHostVersion = 0
Host version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
EHost mHost = kHostUninit
Host that has been identified, see EHost enum.
EAPI mAPI
API of this instance.
bool mHasUI = false
true if the plug-in has a user interface.
int mWidth = 0
The default width of the plug-in UI if it has an interface.
int mHeight = 0
The default height of the plug-in UI if it has an interface.
WDL_PtrList< const char > mParamGroups
A list of unique cstrings found specified as "parameter groups" when defining IParams.
WDL_PtrList< IPreset > mPresets
WDL_Mutex mParams_mutex
Lock when accessing mParams (including via GetParam) from the audio thread.
Protected Attributes inherited from IDelegate
WDL_PtrList< IParam > mParams
A list of IParam objects.
Protected Attributes inherited from IPlugProcessor< PLUG_SAMPLE_DST >
NChanDelayLine< PLUG_SAMPLE_DST > * mLatencyDelay
Pointer to a multichannel delay line used to delay the bypassed signal when a plug-in with latency is bypassed.
Detailed Description
Standalone application base class for an IPlug plug-in, inherits from IPlugBase.
Definition at line 35 of file IPlugAPP.h.
Member Function Documentation
void IPlugAPP::BeginInformHostOfParamChange (int paramIdx) inline override virtual
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Reimplemented from IPlugBase.
Definition at line 42 of file IPlugAPP.h.
void IPlugAPP::EndInformHostOfParamChange (int paramIdx) inline override virtual
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Reimplemented from IPlugBase.
Definition at line 44 of file IPlugAPP.h.
void IPlugAPP::InformHostOfParamChange (int paramIdx, double normalizedValue) inline override virtual
Implemented by the API class, called by the UI via SetParameterValue() with the value of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
normalizedValue The new normalised value of the parameter being changed
Reimplemented from IPlugBase.
Definition at line 43 of file IPlugAPP.h.
void IPlugAPP::ResizeGraphics () override virtual
Call this method in order to notify the API of a graphics resize.
Reimplemented from IPlugBase.
Definition at line 23 of file IPlugAPP.cpp.
References IPluginDelegate::HasUI(), IPluginDelegate::Height(), IPlugBase::OnWindowResize(), and IPluginDelegate::Width().
bool IPlugAPP::SendMidiMsg (const IMidiMsg & msg) override virtual
Send a single MIDI message.
Parameters
msg The IMidiMsg to send
Returns
true if successful
Implements IPlugProcessor< PLUG_SAMPLE_DST >.
Definition at line 37 of file IPlugAPP.cpp.
References IPlugProcessor< PLUG_SAMPLE_DST >::DoesMIDI().
bool IPlugAPP::SendSysEx (ISysEx & msg) override virtual
Send a single MIDI System Exclusive (SysEx) message.
Parameters
msg The ISysEx to send
Returns
true if successful
Reimplemented from IPlugProcessor< PLUG_SAMPLE_DST >.
Definition at line 58 of file IPlugAPP.cpp.
The documentation for this class was generated from the following files:
IPlugAPP.h
IPlugAPP.cpp